# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CommitteeTotalsHouseSenate")

model.instance <- CommitteeTotalsHouseSenate$new()

test_that("all_other_loans", {
  # tests for the property `all_other_loans` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`all_other_loans`, "EXPECTED_RESULT")
})

test_that("candidate_contribution", {
  # tests for the property `candidate_contribution` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`candidate_contribution`, "EXPECTED_RESULT")
})

test_that("cash_on_hand_beginning_period", {
  # tests for the property `cash_on_hand_beginning_period` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`cash_on_hand_beginning_period`, "EXPECTED_RESULT")
})

test_that("committee_designation", {
  # tests for the property `committee_designation` (character)
  # The one-letter designation code of the organization:          - A authorized by a candidate          - J joint fundraising committee          - P principal campaign committee of a candidate          - U unauthorized          - B lobbyist/registrant PAC          - D leadership PAC 

  # uncomment below to test the property 
  #expect_equal(model.instance$`committee_designation`, "EXPECTED_RESULT")
})

test_that("committee_designation_full", {
  # tests for the property `committee_designation_full` (character)
  # The one-letter designation code of the organization:          - A authorized by a candidate          - J joint fundraising committee          - P principal campaign committee of a candidate          - U unauthorized          - B lobbyist/registrant PAC          - D leadership PAC 

  # uncomment below to test the property 
  #expect_equal(model.instance$`committee_designation_full`, "EXPECTED_RESULT")
})

test_that("committee_id", {
  # tests for the property `committee_id` (character)
  #  A unique identifier assigned to each committee or filer registered with the FEC. In general committee id&#39;s begin with the letter C which is followed by eight digits. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`committee_id`, "EXPECTED_RESULT")
})

test_that("committee_name", {
  # tests for the property `committee_name` (character)
  # The name of the committee. If a committee changes its name,     the most recent name will be shown. Committee names are not unique. Use committee_id     for looking up records.

  # uncomment below to test the property 
  #expect_equal(model.instance$`committee_name`, "EXPECTED_RESULT")
})

test_that("committee_state", {
  # tests for the property `committee_state` (character)
  #  State of the committee&#39;s address as filed on the Form 1 

  # uncomment below to test the property 
  #expect_equal(model.instance$`committee_state`, "EXPECTED_RESULT")
})

test_that("committee_type", {
  # tests for the property `committee_type` (character)
  # The one-letter type code of the organization:         - C communication cost         - D delegate         - E electioneering communication         - H House         - I independent expenditor (person or group)         - N PAC - nonqualified         - O independent expenditure-only (super PACs)         - P presidential         - Q PAC - qualified         - S Senate         - U single candidate independent expenditure         - V PAC with non-contribution account, nonqualified         - W PAC with non-contribution account, qualified         - X party, nonqualified         - Y party, qualified         - Z national party non-federal account 

  # uncomment below to test the property 
  #expect_equal(model.instance$`committee_type`, "EXPECTED_RESULT")
})

test_that("committee_type_full", {
  # tests for the property `committee_type_full` (character)
  # The one-letter type code of the organization:         - C communication cost         - D delegate         - E electioneering communication         - H House         - I independent expenditor (person or group)         - N PAC - nonqualified         - O independent expenditure-only (super PACs)         - P presidential         - Q PAC - qualified         - S Senate         - U single candidate independent expenditure         - V PAC with non-contribution account, nonqualified         - W PAC with non-contribution account, qualified         - X party, nonqualified         - Y party, qualified         - Z national party non-federal account 

  # uncomment below to test the property 
  #expect_equal(model.instance$`committee_type_full`, "EXPECTED_RESULT")
})

test_that("contribution_refunds", {
  # tests for the property `contribution_refunds` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`contribution_refunds`, "EXPECTED_RESULT")
})

test_that("contributions", {
  # tests for the property `contributions` (numeric)
  # Contribution

  # uncomment below to test the property 
  #expect_equal(model.instance$`contributions`, "EXPECTED_RESULT")
})

test_that("contributions_ie_and_party_expenditures_made_percent", {
  # tests for the property `contributions_ie_and_party_expenditures_made_percent` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`contributions_ie_and_party_expenditures_made_percent`, "EXPECTED_RESULT")
})

test_that("coverage_end_date", {
  # tests for the property `coverage_end_date` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`coverage_end_date`, "EXPECTED_RESULT")
})

test_that("coverage_start_date", {
  # tests for the property `coverage_start_date` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`coverage_start_date`, "EXPECTED_RESULT")
})

test_that("cycle", {
  # tests for the property `cycle` (integer)
  #  Filter records to only those that are applicable to a given two-year period. This cycle follows the traditional House election cycle and subdivides the presidential and Senate elections into comparable two-year blocks. The cycle begins with an odd year and is named for its ending, even year. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`cycle`, "EXPECTED_RESULT")
})

test_that("disbursements", {
  # tests for the property `disbursements` (numeric)
  # Disbursements

  # uncomment below to test the property 
  #expect_equal(model.instance$`disbursements`, "EXPECTED_RESULT")
})

test_that("filing_frequency", {
  # tests for the property `filing_frequency` (character)
  # The one-letter      code of the filing frequency:          - A Administratively terminated          - D Debt          - M Monthly filer          - Q Quarterly filer          - T Terminated          - W Waived 

  # uncomment below to test the property 
  #expect_equal(model.instance$`filing_frequency`, "EXPECTED_RESULT")
})

test_that("filing_frequency_full", {
  # tests for the property `filing_frequency_full` (character)
  # The one-letter      code of the filing frequency:          - A Administratively terminated          - D Debt          - M Monthly filer          - Q Quarterly filer          - T Terminated          - W Waived 

  # uncomment below to test the property 
  #expect_equal(model.instance$`filing_frequency_full`, "EXPECTED_RESULT")
})

test_that("first_file_date", {
  # tests for the property `first_file_date` (character)
  # The day the FEC received the committee&#39;s first filing. This is usually a Form 1 committee registration.

  # uncomment below to test the property 
  #expect_equal(model.instance$`first_file_date`, "EXPECTED_RESULT")
})

test_that("individual_contributions", {
  # tests for the property `individual_contributions` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`individual_contributions`, "EXPECTED_RESULT")
})

test_that("individual_contributions_percent", {
  # tests for the property `individual_contributions_percent` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`individual_contributions_percent`, "EXPECTED_RESULT")
})

test_that("individual_itemized_contributions", {
  # tests for the property `individual_itemized_contributions` (numeric)
  # Individual itemized contributions are from individuals whose aggregate contributions total over $200 per individual per year. Be aware, some filers choose to itemize donations $200 or less.

  # uncomment below to test the property 
  #expect_equal(model.instance$`individual_itemized_contributions`, "EXPECTED_RESULT")
})

test_that("individual_unitemized_contributions", {
  # tests for the property `individual_unitemized_contributions` (numeric)
  # Unitemized contributions are made individuals whose aggregate contributions total $200 or less per individual per year. Be aware, some filers choose to itemize donations $200 or less and in that case those donations will appear in the itemized total.

  # uncomment below to test the property 
  #expect_equal(model.instance$`individual_unitemized_contributions`, "EXPECTED_RESULT")
})

test_that("last_beginning_image_number", {
  # tests for the property `last_beginning_image_number` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`last_beginning_image_number`, "EXPECTED_RESULT")
})

test_that("last_cash_on_hand_end_period", {
  # tests for the property `last_cash_on_hand_end_period` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`last_cash_on_hand_end_period`, "EXPECTED_RESULT")
})

test_that("last_debts_owed_by_committee", {
  # tests for the property `last_debts_owed_by_committee` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`last_debts_owed_by_committee`, "EXPECTED_RESULT")
})

test_that("last_debts_owed_to_committee", {
  # tests for the property `last_debts_owed_to_committee` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`last_debts_owed_to_committee`, "EXPECTED_RESULT")
})

test_that("last_report_type_full", {
  # tests for the property `last_report_type_full` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`last_report_type_full`, "EXPECTED_RESULT")
})

test_that("last_report_year", {
  # tests for the property `last_report_year` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`last_report_year`, "EXPECTED_RESULT")
})

test_that("loan_repayments", {
  # tests for the property `loan_repayments` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`loan_repayments`, "EXPECTED_RESULT")
})

test_that("loan_repayments_candidate_loans", {
  # tests for the property `loan_repayments_candidate_loans` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`loan_repayments_candidate_loans`, "EXPECTED_RESULT")
})

test_that("loan_repayments_other_loans", {
  # tests for the property `loan_repayments_other_loans` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`loan_repayments_other_loans`, "EXPECTED_RESULT")
})

test_that("loans", {
  # tests for the property `loans` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`loans`, "EXPECTED_RESULT")
})

test_that("loans_made_by_candidate", {
  # tests for the property `loans_made_by_candidate` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`loans_made_by_candidate`, "EXPECTED_RESULT")
})

test_that("net_contributions", {
  # tests for the property `net_contributions` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`net_contributions`, "EXPECTED_RESULT")
})

test_that("net_operating_expenditures", {
  # tests for the property `net_operating_expenditures` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`net_operating_expenditures`, "EXPECTED_RESULT")
})

test_that("offsets_to_operating_expenditures", {
  # tests for the property `offsets_to_operating_expenditures` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`offsets_to_operating_expenditures`, "EXPECTED_RESULT")
})

test_that("operating_expenditures", {
  # tests for the property `operating_expenditures` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`operating_expenditures`, "EXPECTED_RESULT")
})

test_that("operating_expenditures_percent", {
  # tests for the property `operating_expenditures_percent` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`operating_expenditures_percent`, "EXPECTED_RESULT")
})

test_that("other_disbursements", {
  # tests for the property `other_disbursements` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`other_disbursements`, "EXPECTED_RESULT")
})

test_that("other_political_committee_contributions", {
  # tests for the property `other_political_committee_contributions` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`other_political_committee_contributions`, "EXPECTED_RESULT")
})

test_that("other_receipts", {
  # tests for the property `other_receipts` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`other_receipts`, "EXPECTED_RESULT")
})

test_that("party_and_other_committee_contributions_percent", {
  # tests for the property `party_and_other_committee_contributions_percent` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`party_and_other_committee_contributions_percent`, "EXPECTED_RESULT")
})

test_that("party_full", {
  # tests for the property `party_full` (character)
  # Party affiliated with a candidate or committee

  # uncomment below to test the property 
  #expect_equal(model.instance$`party_full`, "EXPECTED_RESULT")
})

test_that("pdf_url", {
  # tests for the property `pdf_url` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`pdf_url`, "EXPECTED_RESULT")
})

test_that("political_party_committee_contributions", {
  # tests for the property `political_party_committee_contributions` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`political_party_committee_contributions`, "EXPECTED_RESULT")
})

test_that("receipts", {
  # tests for the property `receipts` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`receipts`, "EXPECTED_RESULT")
})

test_that("refunded_individual_contributions", {
  # tests for the property `refunded_individual_contributions` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`refunded_individual_contributions`, "EXPECTED_RESULT")
})

test_that("refunded_other_political_committee_contributions", {
  # tests for the property `refunded_other_political_committee_contributions` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`refunded_other_political_committee_contributions`, "EXPECTED_RESULT")
})

test_that("refunded_political_party_committee_contributions", {
  # tests for the property `refunded_political_party_committee_contributions` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`refunded_political_party_committee_contributions`, "EXPECTED_RESULT")
})

test_that("report_form", {
  # tests for the property `report_form` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`report_form`, "EXPECTED_RESULT")
})

test_that("transaction_coverage_date", {
  # tests for the property `transaction_coverage_date` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`transaction_coverage_date`, "EXPECTED_RESULT")
})

test_that("transfers_from_other_authorized_committee", {
  # tests for the property `transfers_from_other_authorized_committee` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`transfers_from_other_authorized_committee`, "EXPECTED_RESULT")
})

test_that("transfers_to_other_authorized_committee", {
  # tests for the property `transfers_to_other_authorized_committee` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`transfers_to_other_authorized_committee`, "EXPECTED_RESULT")
})

test_that("treasurer_name", {
  # tests for the property `treasurer_name` (character)
  # Name of the Committee&#39;s treasurer. If multiple treasurers for the committee, the most recent treasurer will be shown.

  # uncomment below to test the property 
  #expect_equal(model.instance$`treasurer_name`, "EXPECTED_RESULT")
})

