# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ScheduleBByRecipientID")

model.instance <- ScheduleBByRecipientID$new()

test_that("committee_id", {
  # tests for the property `committee_id` (character)
  #  A unique identifier assigned to each committee or filer registered with the FEC. In general committee id&#39;s begin with the letter C which is followed by eight digits. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`committee_id`, "EXPECTED_RESULT")
})

test_that("committee_name", {
  # tests for the property `committee_name` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`committee_name`, "EXPECTED_RESULT")
})

test_that("count", {
  # tests for the property `count` (integer)
  #  Number of records making up the total. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`count`, "EXPECTED_RESULT")
})

test_that("cycle", {
  # tests for the property `cycle` (integer)
  #  Filter records to only those that were applicable to a given two-year period.The cycle begins with an odd year and is named for its ending, even year. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`cycle`, "EXPECTED_RESULT")
})

test_that("memo_count", {
  # tests for the property `memo_count` (integer)
  #  Number of records making up the total. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`memo_count`, "EXPECTED_RESULT")
})

test_that("memo_total", {
  # tests for the property `memo_total` (numeric)
  #  Schedule B disbursements aggregated by memoed items only 

  # uncomment below to test the property 
  #expect_equal(model.instance$`memo_total`, "EXPECTED_RESULT")
})

test_that("recipient_id", {
  # tests for the property `recipient_id` (character)
  # The FEC identifier should be represented here if the entity receiving the disbursement is registered with the FEC.

  # uncomment below to test the property 
  #expect_equal(model.instance$`recipient_id`, "EXPECTED_RESULT")
})

test_that("recipient_name", {
  # tests for the property `recipient_name` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`recipient_name`, "EXPECTED_RESULT")
})

test_that("total", {
  # tests for the property `total` (numeric)
  #  Schedule B disbursements aggregated by non-memoed items only 

  # uncomment below to test the property 
  #expect_equal(model.instance$`total`, "EXPECTED_RESULT")
})

