# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CandidateTotalPage")

model.instance <- CandidateTotalPage$new()

test_that("pagination", {
  # tests for the property `pagination` (OffsetInfo)

  # uncomment below to test the property 
  #expect_equal(model.instance$`pagination`, "EXPECTED_RESULT")
})

test_that("results", {
  # tests for the property `results` (array[CandidateTotal])

  # uncomment below to test the property 
  #expect_equal(model.instance$`results`, "EXPECTED_RESULT")
})

