# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CommunicationCost")

model.instance <- CommunicationCost$new()

test_that("action_code", {
  # tests for the property `action_code` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`action_code`, "EXPECTED_RESULT")
})

test_that("action_code_full", {
  # tests for the property `action_code_full` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`action_code_full`, "EXPECTED_RESULT")
})

test_that("candidate_first_name", {
  # tests for the property `candidate_first_name` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`candidate_first_name`, "EXPECTED_RESULT")
})

test_that("candidate_id", {
  # tests for the property `candidate_id` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`candidate_id`, "EXPECTED_RESULT")
})

test_that("candidate_last_name", {
  # tests for the property `candidate_last_name` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`candidate_last_name`, "EXPECTED_RESULT")
})

test_that("candidate_middle_name", {
  # tests for the property `candidate_middle_name` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`candidate_middle_name`, "EXPECTED_RESULT")
})

test_that("candidate_name", {
  # tests for the property `candidate_name` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`candidate_name`, "EXPECTED_RESULT")
})

test_that("candidate_office", {
  # tests for the property `candidate_office` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`candidate_office`, "EXPECTED_RESULT")
})

test_that("candidate_office_district", {
  # tests for the property `candidate_office_district` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`candidate_office_district`, "EXPECTED_RESULT")
})

test_that("candidate_office_full", {
  # tests for the property `candidate_office_full` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`candidate_office_full`, "EXPECTED_RESULT")
})

test_that("candidate_office_state", {
  # tests for the property `candidate_office_state` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`candidate_office_state`, "EXPECTED_RESULT")
})

test_that("committee_id", {
  # tests for the property `committee_id` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`committee_id`, "EXPECTED_RESULT")
})

test_that("committee_name", {
  # tests for the property `committee_name` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`committee_name`, "EXPECTED_RESULT")
})

test_that("communication_class", {
  # tests for the property `communication_class` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`communication_class`, "EXPECTED_RESULT")
})

test_that("communication_type", {
  # tests for the property `communication_type` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`communication_type`, "EXPECTED_RESULT")
})

test_that("communication_type_full", {
  # tests for the property `communication_type_full` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`communication_type_full`, "EXPECTED_RESULT")
})

test_that("cycle", {
  # tests for the property `cycle` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`cycle`, "EXPECTED_RESULT")
})

test_that("file_number", {
  # tests for the property `file_number` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`file_number`, "EXPECTED_RESULT")
})

test_that("form_type_code", {
  # tests for the property `form_type_code` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`form_type_code`, "EXPECTED_RESULT")
})

test_that("image_number", {
  # tests for the property `image_number` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`image_number`, "EXPECTED_RESULT")
})

test_that("original_sub_id", {
  # tests for the property `original_sub_id` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`original_sub_id`, "EXPECTED_RESULT")
})

test_that("pdf_url", {
  # tests for the property `pdf_url` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`pdf_url`, "EXPECTED_RESULT")
})

test_that("primary_general_indicator", {
  # tests for the property `primary_general_indicator` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`primary_general_indicator`, "EXPECTED_RESULT")
})

test_that("primary_general_indicator_description", {
  # tests for the property `primary_general_indicator_description` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`primary_general_indicator_description`, "EXPECTED_RESULT")
})

test_that("purpose", {
  # tests for the property `purpose` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`purpose`, "EXPECTED_RESULT")
})

test_that("report_type", {
  # tests for the property `report_type` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`report_type`, "EXPECTED_RESULT")
})

test_that("report_year", {
  # tests for the property `report_year` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`report_year`, "EXPECTED_RESULT")
})

test_that("schedule_type", {
  # tests for the property `schedule_type` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`schedule_type`, "EXPECTED_RESULT")
})

test_that("schedule_type_full", {
  # tests for the property `schedule_type_full` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`schedule_type_full`, "EXPECTED_RESULT")
})

test_that("state_full", {
  # tests for the property `state_full` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`state_full`, "EXPECTED_RESULT")
})

test_that("sub_id", {
  # tests for the property `sub_id` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`sub_id`, "EXPECTED_RESULT")
})

test_that("support_oppose_indicator", {
  # tests for the property `support_oppose_indicator` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`support_oppose_indicator`, "EXPECTED_RESULT")
})

test_that("tran_id", {
  # tests for the property `tran_id` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`tran_id`, "EXPECTED_RESULT")
})

test_that("transaction_amount", {
  # tests for the property `transaction_amount` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`transaction_amount`, "EXPECTED_RESULT")
})

test_that("transaction_date", {
  # tests for the property `transaction_date` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`transaction_date`, "EXPECTED_RESULT")
})

test_that("transaction_type", {
  # tests for the property `transaction_type` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`transaction_type`, "EXPECTED_RESULT")
})

