# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InlineResponseDefault1Documents1")

model.instance <- InlineResponseDefault1Documents1$new()

test_that("category", {
  # tests for the property `category` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`category`, "EXPECTED_RESULT")
})

test_that("date", {
  # tests for the property `date` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`date`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("document_id", {
  # tests for the property `document_id` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`document_id`, "EXPECTED_RESULT")
})

test_that("url", {
  # tests for the property `url` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`url`, "EXPECTED_RESULT")
})

