# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InlineResponseDefault1")

model.instance <- InlineResponseDefault1$new()

test_that("admin_fines", {
  # tests for the property `admin_fines` (array[InlineResponseDefault1AdminFines])

  # uncomment below to test the property 
  #expect_equal(model.instance$`admin_fines`, "EXPECTED_RESULT")
})

test_that("adrs", {
  # tests for the property `adrs` (array[InlineResponseDefault1Adrs])

  # uncomment below to test the property 
  #expect_equal(model.instance$`adrs`, "EXPECTED_RESULT")
})

test_that("advisory_opinions", {
  # tests for the property `advisory_opinions` (array[InlineResponseDefault1AdvisoryOpinions])

  # uncomment below to test the property 
  #expect_equal(model.instance$`advisory_opinions`, "EXPECTED_RESULT")
})

test_that("murs", {
  # tests for the property `murs` (array[InlineResponseDefault1Murs])

  # uncomment below to test the property 
  #expect_equal(model.instance$`murs`, "EXPECTED_RESULT")
})

test_that("regulations", {
  # tests for the property `regulations` (array[InlineResponseDefault1Regulations])

  # uncomment below to test the property 
  #expect_equal(model.instance$`regulations`, "EXPECTED_RESULT")
})

test_that("statutes", {
  # tests for the property `statutes` (array[InlineResponseDefault1Statutes])

  # uncomment below to test the property 
  #expect_equal(model.instance$`statutes`, "EXPECTED_RESULT")
})

test_that("total_admin_fines", {
  # tests for the property `total_admin_fines` (integer)
  # Total number of Admin Fines matching the search criteria

  # uncomment below to test the property 
  #expect_equal(model.instance$`total_admin_fines`, "EXPECTED_RESULT")
})

test_that("total_adrs", {
  # tests for the property `total_adrs` (integer)
  # Total number of ADRs matching the search criteria

  # uncomment below to test the property 
  #expect_equal(model.instance$`total_adrs`, "EXPECTED_RESULT")
})

test_that("total_advisory_opinions", {
  # tests for the property `total_advisory_opinions` (integer)
  # Total number of Advisory Opinions matching the search criteria

  # uncomment below to test the property 
  #expect_equal(model.instance$`total_advisory_opinions`, "EXPECTED_RESULT")
})

test_that("total_all", {
  # tests for the property `total_all` (integer)
  # Total number of legal documents matching the search criteria

  # uncomment below to test the property 
  #expect_equal(model.instance$`total_all`, "EXPECTED_RESULT")
})

test_that("total_murs", {
  # tests for the property `total_murs` (integer)
  # Total number of MURs matching the search criteria

  # uncomment below to test the property 
  #expect_equal(model.instance$`total_murs`, "EXPECTED_RESULT")
})

test_that("total_regulations", {
  # tests for the property `total_regulations` (integer)
  # Total number of Regulations matching the search criteria

  # uncomment below to test the property 
  #expect_equal(model.instance$`total_regulations`, "EXPECTED_RESULT")
})

test_that("total_statutes", {
  # tests for the property `total_statutes` (integer)
  # Total number of Statutes matching the search criteria

  # uncomment below to test the property 
  #expect_equal(model.instance$`total_statutes`, "EXPECTED_RESULT")
})

