# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ScheduleEByCandidate")

model.instance <- ScheduleEByCandidate$new()

test_that("candidate_id", {
  # tests for the property `candidate_id` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`candidate_id`, "EXPECTED_RESULT")
})

test_that("candidate_name", {
  # tests for the property `candidate_name` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`candidate_name`, "EXPECTED_RESULT")
})

test_that("committee_id", {
  # tests for the property `committee_id` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`committee_id`, "EXPECTED_RESULT")
})

test_that("committee_name", {
  # tests for the property `committee_name` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`committee_name`, "EXPECTED_RESULT")
})

test_that("count", {
  # tests for the property `count` (integer)
  #  Number of records making up the total. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`count`, "EXPECTED_RESULT")
})

test_that("cycle", {
  # tests for the property `cycle` (integer)
  #  Filter records to only those that were applicable to a given two-year period.The cycle begins with an odd year and is named for its ending, even year. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`cycle`, "EXPECTED_RESULT")
})

test_that("support_oppose_indicator", {
  # tests for the property `support_oppose_indicator` (character)
  # Explains if the money was spent in order to support or oppose a candidate or candidates. (Coded S or O for support or oppose.) This indicator applies to independent expenditures and communication costs.

  # uncomment below to test the property 
  #expect_equal(model.instance$`support_oppose_indicator`, "EXPECTED_RESULT")
})

test_that("total", {
  # tests for the property `total` (numeric)
  # Sum of transactions

  # uncomment below to test the property 
  #expect_equal(model.instance$`total`, "EXPECTED_RESULT")
})

