# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test EFilings")

model.instance <- EFilings$new()

test_that("amended_by", {
  # tests for the property `amended_by` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`amended_by`, "EXPECTED_RESULT")
})

test_that("amendment_chain", {
  # tests for the property `amendment_chain` (array[integer])

  # uncomment below to test the property 
  #expect_equal(model.instance$`amendment_chain`, "EXPECTED_RESULT")
})

test_that("amendment_number", {
  # tests for the property `amendment_number` (integer)
  #  Number of times the report has been amended. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`amendment_number`, "EXPECTED_RESULT")
})

test_that("amends_file", {
  # tests for the property `amends_file` (integer)
  #  For amendments, this file_number is the file_number of the previous report that is being amended. Refer to the amended_by for the most recent version of the report. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`amends_file`, "EXPECTED_RESULT")
})

test_that("beginning_image_number", {
  # tests for the property `beginning_image_number` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`beginning_image_number`, "EXPECTED_RESULT")
})

test_that("committee_id", {
  # tests for the property `committee_id` (character)
  #  A unique identifier assigned to each committee or filer registered with the FEC. In general committee id&#39;s begin with the letter C which is followed by eight digits. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`committee_id`, "EXPECTED_RESULT")
})

test_that("committee_name", {
  # tests for the property `committee_name` (character)
  # The name of the committee. If a committee changes its name,     the most recent name will be shown. Committee names are not unique. Use committee_id     for looking up records.

  # uncomment below to test the property 
  #expect_equal(model.instance$`committee_name`, "EXPECTED_RESULT")
})

test_that("coverage_end_date", {
  # tests for the property `coverage_end_date` (character)
  # Ending date of the reporting period

  # uncomment below to test the property 
  #expect_equal(model.instance$`coverage_end_date`, "EXPECTED_RESULT")
})

test_that("coverage_start_date", {
  # tests for the property `coverage_start_date` (character)
  # Beginning date of the reporting period

  # uncomment below to test the property 
  #expect_equal(model.instance$`coverage_start_date`, "EXPECTED_RESULT")
})

test_that("csv_url", {
  # tests for the property `csv_url` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`csv_url`, "EXPECTED_RESULT")
})

test_that("document_description", {
  # tests for the property `document_description` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`document_description`, "EXPECTED_RESULT")
})

test_that("ending_image_number", {
  # tests for the property `ending_image_number` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`ending_image_number`, "EXPECTED_RESULT")
})

test_that("fec_file_id", {
  # tests for the property `fec_file_id` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`fec_file_id`, "EXPECTED_RESULT")
})

test_that("fec_url", {
  # tests for the property `fec_url` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`fec_url`, "EXPECTED_RESULT")
})

test_that("file_number", {
  # tests for the property `file_number` (integer)
  # Filing ID number

  # uncomment below to test the property 
  #expect_equal(model.instance$`file_number`, "EXPECTED_RESULT")
})

test_that("filed_date", {
  # tests for the property `filed_date` (character)
  # Timestamp of electronic or paper record that FEC received

  # uncomment below to test the property 
  #expect_equal(model.instance$`filed_date`, "EXPECTED_RESULT")
})

test_that("form_type", {
  # tests for the property `form_type` (character)
  # The form where the underlying data comes from, for example, Form 1 would appear as F1:     - F1   Statement of Organization     - F1M  Notification of Multicandidate Status     - F2   Statement of Candidacy     - F3   Report of Receipts and Disbursements for an Authorized Committee     - F3P  Report of Receipts and Disbursements by an Authorized Committee of a Candidate for     The Office of President or Vice President     - F3L  Report of Contributions Bundled by Lobbyists/Registrants and Lobbyist/Registrant PACs     - F3X  Report of Receipts and Disbursements for other than an Authorized Committee     - F4   Report of Receipts and Disbursements for a Committee or Organization Supporting a Nomination Convention     - F5   Report of Independent Expenditures Made and Contributions Received     - F6   48 Hour Notice of Contributions/Loans Received     - F7   Report of Communication Costs by Corporations and Membership Organizations     - F8   Debt Settlement Plan     - F9   24 Hour Notice of Disbursements for Electioneering Communications     - F13  Report of Donations Accepted for Inaugural Committee     - F99  Miscellaneous Text     - FRQ  Request for Additional Information 

  # uncomment below to test the property 
  #expect_equal(model.instance$`form_type`, "EXPECTED_RESULT")
})

test_that("html_url", {
  # tests for the property `html_url` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`html_url`, "EXPECTED_RESULT")
})

test_that("is_amended", {
  # tests for the property `is_amended` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`is_amended`, "EXPECTED_RESULT")
})

test_that("load_timestamp", {
  # tests for the property `load_timestamp` (character)
  # Date the information was loaded into the FEC systems. This can be affected by reseting systems and other factors, refer to receipt_date for the day that the FEC received the paper or electronic document. Keep in mind that paper filings take more time to process and there can be a lag between load_date and receipt_date. This field can be helpful to identify paper records that have been processed recently.

  # uncomment below to test the property 
  #expect_equal(model.instance$`load_timestamp`, "EXPECTED_RESULT")
})

test_that("most_recent", {
  # tests for the property `most_recent` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`most_recent`, "EXPECTED_RESULT")
})

test_that("most_recent_filing", {
  # tests for the property `most_recent_filing` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`most_recent_filing`, "EXPECTED_RESULT")
})

test_that("pdf_url", {
  # tests for the property `pdf_url` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`pdf_url`, "EXPECTED_RESULT")
})

test_that("receipt_date", {
  # tests for the property `receipt_date` (character)
  # Date the FEC received the electronic or paper record

  # uncomment below to test the property 
  #expect_equal(model.instance$`receipt_date`, "EXPECTED_RESULT")
})

