# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CommitteeSearchList")

model.instance <- CommitteeSearchList$new()

test_that("results", {
  # tests for the property `results` (array[CommitteeSearch])

  # uncomment below to test the property 
  #expect_equal(model.instance$`results`, "EXPECTED_RESULT")
})

