# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ElectionsList")

model.instance <- ElectionsList$new()

test_that("cycle", {
  # tests for the property `cycle` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`cycle`, "EXPECTED_RESULT")
})

test_that("district", {
  # tests for the property `district` (character)
  # Two-digit US House distirict of the office the candidate is running for. Presidential, Senate and House at-large candidates will have District 00.

  # uncomment below to test the property 
  #expect_equal(model.instance$`district`, "EXPECTED_RESULT")
})

test_that("office", {
  # tests for the property `office` (character)
  # Federal office candidate runs for: H, S or P

  # uncomment below to test the property 
  #expect_equal(model.instance$`office`, "EXPECTED_RESULT")
})

test_that("state", {
  # tests for the property `state` (character)
  # US state or territory

  # uncomment below to test the property 
  #expect_equal(model.instance$`state`, "EXPECTED_RESULT")
})

