# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CandidateCommitteeTotalsPresidential")

model.instance <- CandidateCommitteeTotalsPresidential$new()

test_that("candidate_contribution", {
  # tests for the property `candidate_contribution` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`candidate_contribution`, "EXPECTED_RESULT")
})

test_that("candidate_election_year", {
  # tests for the property `candidate_election_year` (integer)
  #  Filter records to only those that are applicable to a given two-year period. This cycle follows the traditional House election cycle and subdivides the presidential and Senate elections into comparable two-year blocks. The cycle begins with an odd year and is named for its ending, even year. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`candidate_election_year`, "EXPECTED_RESULT")
})

test_that("candidate_id", {
  # tests for the property `candidate_id` (character)
  #  A unique identifier assigned to each candidate registered with the FEC. If a person runs for several offices, that person will have separate candidate IDs for each office. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`candidate_id`, "EXPECTED_RESULT")
})

test_that("contribution_refunds", {
  # tests for the property `contribution_refunds` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`contribution_refunds`, "EXPECTED_RESULT")
})

test_that("contributions", {
  # tests for the property `contributions` (numeric)
  # Contribution

  # uncomment below to test the property 
  #expect_equal(model.instance$`contributions`, "EXPECTED_RESULT")
})

test_that("coverage_end_date", {
  # tests for the property `coverage_end_date` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`coverage_end_date`, "EXPECTED_RESULT")
})

test_that("coverage_start_date", {
  # tests for the property `coverage_start_date` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`coverage_start_date`, "EXPECTED_RESULT")
})

test_that("cycle", {
  # tests for the property `cycle` (integer)
  #  Filter records to only those that are applicable to a given two-year period. This cycle follows the traditional House election cycle and subdivides the presidential and Senate elections into comparable two-year blocks. The cycle begins with an odd year and is named for its ending, even year. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`cycle`, "EXPECTED_RESULT")
})

test_that("disbursements", {
  # tests for the property `disbursements` (numeric)
  # Disbursements

  # uncomment below to test the property 
  #expect_equal(model.instance$`disbursements`, "EXPECTED_RESULT")
})

test_that("election_full", {
  # tests for the property `election_full` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`election_full`, "EXPECTED_RESULT")
})

test_that("exempt_legal_accounting_disbursement", {
  # tests for the property `exempt_legal_accounting_disbursement` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`exempt_legal_accounting_disbursement`, "EXPECTED_RESULT")
})

test_that("federal_funds", {
  # tests for the property `federal_funds` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`federal_funds`, "EXPECTED_RESULT")
})

test_that("fundraising_disbursements", {
  # tests for the property `fundraising_disbursements` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`fundraising_disbursements`, "EXPECTED_RESULT")
})

test_that("individual_contributions", {
  # tests for the property `individual_contributions` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`individual_contributions`, "EXPECTED_RESULT")
})

test_that("individual_itemized_contributions", {
  # tests for the property `individual_itemized_contributions` (numeric)
  # Individual itemized contributions are from individuals whose aggregate contributions total over $200 per individual per year. Be aware, some filers choose to itemize donations $200 or less.

  # uncomment below to test the property 
  #expect_equal(model.instance$`individual_itemized_contributions`, "EXPECTED_RESULT")
})

test_that("individual_unitemized_contributions", {
  # tests for the property `individual_unitemized_contributions` (numeric)
  # Unitemized contributions are made individuals whose aggregate contributions total $200 or less per individual per year. Be aware, some filers choose to itemize donations $200 or less and in that case those donations will appear in the itemized total.

  # uncomment below to test the property 
  #expect_equal(model.instance$`individual_unitemized_contributions`, "EXPECTED_RESULT")
})

test_that("last_beginning_image_number", {
  # tests for the property `last_beginning_image_number` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`last_beginning_image_number`, "EXPECTED_RESULT")
})

test_that("last_cash_on_hand_end_period", {
  # tests for the property `last_cash_on_hand_end_period` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`last_cash_on_hand_end_period`, "EXPECTED_RESULT")
})

test_that("last_debts_owed_by_committee", {
  # tests for the property `last_debts_owed_by_committee` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`last_debts_owed_by_committee`, "EXPECTED_RESULT")
})

test_that("last_debts_owed_to_committee", {
  # tests for the property `last_debts_owed_to_committee` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`last_debts_owed_to_committee`, "EXPECTED_RESULT")
})

test_that("last_report_type_full", {
  # tests for the property `last_report_type_full` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`last_report_type_full`, "EXPECTED_RESULT")
})

test_that("last_report_year", {
  # tests for the property `last_report_year` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`last_report_year`, "EXPECTED_RESULT")
})

test_that("loan_repayments_made", {
  # tests for the property `loan_repayments_made` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`loan_repayments_made`, "EXPECTED_RESULT")
})

test_that("loans_received", {
  # tests for the property `loans_received` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`loans_received`, "EXPECTED_RESULT")
})

test_that("loans_received_from_candidate", {
  # tests for the property `loans_received_from_candidate` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`loans_received_from_candidate`, "EXPECTED_RESULT")
})

test_that("net_contributions", {
  # tests for the property `net_contributions` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`net_contributions`, "EXPECTED_RESULT")
})

test_that("net_operating_expenditures", {
  # tests for the property `net_operating_expenditures` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`net_operating_expenditures`, "EXPECTED_RESULT")
})

test_that("offsets_to_fundraising_expenditures", {
  # tests for the property `offsets_to_fundraising_expenditures` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`offsets_to_fundraising_expenditures`, "EXPECTED_RESULT")
})

test_that("offsets_to_legal_accounting", {
  # tests for the property `offsets_to_legal_accounting` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`offsets_to_legal_accounting`, "EXPECTED_RESULT")
})

test_that("offsets_to_operating_expenditures", {
  # tests for the property `offsets_to_operating_expenditures` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`offsets_to_operating_expenditures`, "EXPECTED_RESULT")
})

test_that("operating_expenditures", {
  # tests for the property `operating_expenditures` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`operating_expenditures`, "EXPECTED_RESULT")
})

test_that("other_disbursements", {
  # tests for the property `other_disbursements` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`other_disbursements`, "EXPECTED_RESULT")
})

test_that("other_loans_received", {
  # tests for the property `other_loans_received` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`other_loans_received`, "EXPECTED_RESULT")
})

test_that("other_political_committee_contributions", {
  # tests for the property `other_political_committee_contributions` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`other_political_committee_contributions`, "EXPECTED_RESULT")
})

test_that("other_receipts", {
  # tests for the property `other_receipts` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`other_receipts`, "EXPECTED_RESULT")
})

test_that("political_party_committee_contributions", {
  # tests for the property `political_party_committee_contributions` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`political_party_committee_contributions`, "EXPECTED_RESULT")
})

test_that("receipts", {
  # tests for the property `receipts` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`receipts`, "EXPECTED_RESULT")
})

test_that("refunded_individual_contributions", {
  # tests for the property `refunded_individual_contributions` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`refunded_individual_contributions`, "EXPECTED_RESULT")
})

test_that("refunded_other_political_committee_contributions", {
  # tests for the property `refunded_other_political_committee_contributions` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`refunded_other_political_committee_contributions`, "EXPECTED_RESULT")
})

test_that("refunded_political_party_committee_contributions", {
  # tests for the property `refunded_political_party_committee_contributions` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`refunded_political_party_committee_contributions`, "EXPECTED_RESULT")
})

test_that("repayments_loans_made_by_candidate", {
  # tests for the property `repayments_loans_made_by_candidate` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`repayments_loans_made_by_candidate`, "EXPECTED_RESULT")
})

test_that("repayments_other_loans", {
  # tests for the property `repayments_other_loans` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`repayments_other_loans`, "EXPECTED_RESULT")
})

test_that("total_offsets_to_operating_expenditures", {
  # tests for the property `total_offsets_to_operating_expenditures` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`total_offsets_to_operating_expenditures`, "EXPECTED_RESULT")
})

test_that("transaction_coverage_date", {
  # tests for the property `transaction_coverage_date` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`transaction_coverage_date`, "EXPECTED_RESULT")
})

test_that("transfers_from_affiliated_committee", {
  # tests for the property `transfers_from_affiliated_committee` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`transfers_from_affiliated_committee`, "EXPECTED_RESULT")
})

test_that("transfers_to_other_authorized_committee", {
  # tests for the property `transfers_to_other_authorized_committee` (numeric)

  # uncomment below to test the property 
  #expect_equal(model.instance$`transfers_to_other_authorized_committee`, "EXPECTED_RESULT")
})

